# Generated by Django 2.2 on 2020-01-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='страна')),
            ],
            options={
                'verbose_name_plural': 'страны',
                'verbose_name': 'страна',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='категория')),
            ],
            options={
                'verbose_name_plural': 'категории',
                'verbose_name': 'категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubRubricOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Подкатегория')),
                ('subrubric', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Rubric')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
                'verbose_name': 'Подкатегория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='область, край')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bboard.Country', verbose_name='страна')),
            ],
            options={
                'verbose_name_plural': 'область, край',
                'verbose_name': 'область, край',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='город')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bboard.State', verbose_name='область, край')),
            ],
            options={
                'verbose_name_plural': 'города',
                'verbose_name': 'город',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('kind', models.CharField(choices=[(None, 'Выберите действие'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], max_length=1, null=True, verbose_name='Действие')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.City', verbose_name='город')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Rubric', verbose_name='Категория')),
                ('subrubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.SubRubricOne', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name_plural': 'объявления',
                'verbose_name': 'объявление',
                'ordering': ['-published'],
            },
        ),
    ]
